/* Build the seed in Node and print a summary: node tests/seed-check.js */
const fs = require('fs'), path = require('path'), vm = require('vm');
const root = path.join(__dirname, '..');
const files = ['js/core/util.js','js/core/i18n.js','js/config/platform.js','js/config/geo.js','js/config/services.js','js/config/ratings.js','js/config/status.js','js/config/defaults.js','js/config/forms.js','js/config/reportForms.js','js/workflow/common.js','js/workflow/validation.js','js/workflow/investigation.js','js/workflow/collection.js','js/workflow/batch.js','js/workflow/sla.js','js/workflow/masking.js','js/workflow/scoring.js','js/workflow/registration.js','js/workflow/reports.js','js/store/store.js','js/store/domain.js','js/store/seed.js'];
const ctx = { console, Intl, Date, Math, JSON, setTimeout, clearTimeout };
ctx.window = ctx; ctx.globalThis = ctx; ctx.localStorage = { getItem: () => null, setItem: () => {} }; ctx.document = { documentElement: {} };
vm.createContext(ctx);
for (const f of files) vm.runInContext(fs.readFileSync(path.join(root, f), 'utf8'), ctx, { filename: f });
const T = Date.now();
const db = ctx.ICM.seed.build(T);
const by = {};
db.cases.forEach(c => { const k = c.service + ':' + c.status; by[k] = (by[k] || 0) + 1; });
console.log('cases', db.cases.length); console.log(by);
console.log('users', db.users.length, 'providers', db.providers.length, 'agents', db.agents.length, 'offers', db.offers.length, 'batches', db.batches.length);
console.log('ratings', db.ratings.length, 'archived', db.ratings.filter(r => r.archived).length, 'client', db.clientRatings.length, 'disputes', db.disputes.length, 'invoices', db.invoices.length, 'notifications', db.notifications.length, 'audit', db.audit.length);
Object.values(db.scores).forEach(s => { const p = db.providers.find(x => x.id === s.providerId); console.log(p.name.padEnd(32), String(s.overall).padEnd(6), p.enforcement.level, Object.values(s.byService).map(b => b.service + ' op=' + b.operational + ' rt=' + b.ratingPart + ' n=' + b.ratingCount).join(' | ')); });
const sla = {}; db.cases.forEach(c => { const s = ctx.ICM.wf.sla.state(c, T); sla[s] = (sla[s] || 0) + 1; }); console.log('sla', sla);
const pr = {}; db.cases.forEach(c => (c.promises || []).forEach(p => pr[p.status] = (pr[p.status] || 0) + 1)); console.log('promises', pr);
console.log('invoices', db.invoices.map(i => i.month + ':' + i.status).join(' '));
console.log('json size KB', Math.round(JSON.stringify(db).length / 1024));
