/* The shared engine scripts, in the same order as prototype/index.html (without the web
   pages). Plain JavaScript so the type checker does not try to read the engine files,
   which are classic scripts rather than modules. */
export const SCRIPTS = [
  () => import("../../../prototype/js/core/util.js"),
  () => import("../../../prototype/js/core/i18n.js"),
  () => import("../../../prototype/js/i18n/en.js"),
  () => import("../../../prototype/js/i18n/ar.js"),
  () => import("../../../prototype/js/i18n/registration.en.js"),
  () => import("../../../prototype/js/i18n/registration.ar.js"),
  () => import("../../../prototype/js/i18n/investigation.en.js"),
  () => import("../../../prototype/js/i18n/investigation.ar.js"),
  () => import("../../../prototype/js/config/platform.js"),
  () => import("../../../prototype/js/config/geo.js"),
  () => import("../../../prototype/js/config/services.js"),
  () => import("../../../prototype/js/config/ratings.js"),
  () => import("../../../prototype/js/config/status.js"),
  () => import("../../../prototype/js/config/defaults.js"),
  () => import("../../../prototype/js/config/forms.js"),
  () => import("../../../prototype/js/config/reportForms.js"),
  () => import("../../../prototype/js/workflow/common.js"),
  () => import("../../../prototype/js/workflow/validation.js"),
  () => import("../../../prototype/js/workflow/investigation.js"),
  () => import("../../../prototype/js/workflow/collection.js"),
  () => import("../../../prototype/js/workflow/batch.js"),
  () => import("../../../prototype/js/workflow/sla.js"),
  () => import("../../../prototype/js/workflow/masking.js"),
  () => import("../../../prototype/js/workflow/scoring.js"),
  () => import("../../../prototype/js/workflow/registration.js"),
  () => import("../../../prototype/js/workflow/settings.js"),
  () => import("../../../prototype/js/workflow/reports.js"),
  () => import("../../../prototype/js/store/store.js"),
  () => import("../../../prototype/js/store/domain.js"),
  () => import("../../../prototype/js/store/seed.js"),
  () => import("../../../prototype/js/services/engine.js"),
  () => import("../../../prototype/js/services/contracts.js"),
  () => import("../../../prototype/js/services/core.js"),
  () => import("../../../prototype/js/services/cases.js"),
  () => import("../../../prototype/js/services/batches.js"),
  () => import("../../../prototype/js/services/providers.js"),
  () => import("../../../prototype/js/services/ratings.js"),
  () => import("../../../prototype/js/services/billing.js"),
  () => import("../../../prototype/js/services/registration.js"),
  () => import("../../../prototype/js/services/exports.js"),
  () => import("../../../prototype/js/services/index.js"),
  () => import("../../../prototype/js/ui/icons.js"),
];
